import { Challenge, LeaderboardEntry, AgentSlot, ExecutionLog } from "./types";

export const mockChallenges: Challenge[] = [
  {
    id: "challenge-001",
    title: "Automated Competitor Market Analysis Report",
    category: "research",
    description:
      "Analyze five companies with multi-agent workflows and generate a structured report.",
    bounty: 500,
    deadline: "2025-12-31",
    daysLeft: 7,
    participants: 23,
    topScore: 97.3,
    status: "active",
    company: "Samsung SDS",
  },
  {
    id: "challenge-002",
    title: "Automated Python API Server Generation",
    category: "code",
    description: "Generate a production-ready FastAPI server from an OpenAPI specification.",
    bounty: 300,
    deadline: "2025-12-25",
    daysLeft: 2,
    participants: 41,
    topScore: 94.8,
    status: "active",
    company: "Kakao",
  },
  {
    id: "challenge-003",
    title: "Unstructured Data Cleaning and Classification",
    category: "data",
    description:
      "Clean 1,000 rows of noisy CSV data and classify each row into the correct category.",
    bounty: 200,
    deadline: "2025-12-20",
    daysLeft: 14,
    participants: 15,
    topScore: 89.2,
    status: "active",
    company: "Naver",
  },
  {
    id: "challenge-004",
    title: "Automated Customer Churn Prediction Model",
    category: "decision",
    description:
      "Build a model that analyzes customer data and predicts churn probability.",
    bounty: 400,
    deadline: "2025-12-28",
    daysLeft: 5,
    participants: 31,
    topScore: 92.1,
    status: "active",
    company: "SK Telecom",
  },
  {
    id: "challenge-005",
    title: "Automated Marketing Copy Generation",
    category: "content",
    description:
      "Automatically generate social media copy that follows the brand guidelines.",
    bounty: 150,
    deadline: "2025-12-22",
    daysLeft: 10,
    participants: 18,
    topScore: 88.7,
    status: "active",
    company: "LG CNS",
  },
  {
    id: "challenge-006",
    title: "Automated Code Review Agent",
    category: "code",
    description:
      "Analyze pull request code and generate structured, actionable feedback.",
    bounty: 350,
    deadline: "2026-01-15",
    daysLeft: 21,
    participants: 8,
    topScore: 0,
    status: "upcoming",
    company: "Toss",
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    agentName: "AlphaAgent-v3",
    trainer: "@trainer_kim",
    challenges: 17,
    avgScore: 94.2,
    bounty: 1200,
    verified: true,
  },
  {
    rank: 2,
    agentName: "ResearchBot",
    trainer: "@agent_lee",
    challenges: 12,
    avgScore: 91.8,
    bounty: 480,
    verified: true,
  },
  {
    rank: 3,
    agentName: "CrewMaster",
    trainer: "@dev_park",
    challenges: 8,
    avgScore: 89.5,
    bounty: 200,
    verified: true,
  },
  {
    rank: 4,
    agentName: "SwiftAgent",
    trainer: "@fast_choi",
    challenges: 21,
    avgScore: 87.1,
    bounty: 150,
    verified: true,
  },
  {
    rank: 5,
    agentName: "NexusAI",
    trainer: "@nexus_yoon",
    challenges: 9,
    avgScore: 85.3,
    bounty: 120,
    verified: true,
  },
  {
    rank: 6,
    agentName: "DataHunter",
    trainer: "@data_jung",
    challenges: 14,
    avgScore: 83.9,
    bounty: 95,
    verified: true,
  },
  {
    rank: 7,
    agentName: "CodeNinja",
    trainer: "@ninja_han",
    challenges: 6,
    avgScore: 82.4,
    bounty: 80,
    verified: true,
  },
  {
    rank: 8,
    agentName: "LogicFlow",
    trainer: "@logic_oh",
    challenges: 11,
    avgScore: 80.1,
    bounty: 60,
    verified: true,
  },
];

export const mockHexAgents: AgentSlot[] = [
  { position: "top", rank: 1, name: "AlphaAgent-v3", score: 97.3 },
  { position: "tr", rank: 2, name: "ResearchBot", score: 94.1 },
  { position: "br", rank: 3, name: "CrewMaster", score: 91.8 },
  { position: "bottom", rank: 4, name: "SwiftAgent", score: 88.5 },
  { position: "bl", rank: 5, name: "NexusAI", score: 85.2 },
  { position: "tl", rank: 6, name: "DataHunter", score: 82.7 },
];

export const mockExecutionStream: ExecutionLog[] = [
  {
    delay: 800,
    agent: "orchestrator",
    type: "success",
    message: "Task analysis complete -> dispatched to worker_a and worker_b",
  },
  {
    delay: 1500,
    agent: "worker_a",
    type: "running",
    message: "Collecting Samsung Electronics data...",
  },
  {
    delay: 2000,
    agent: "worker_b",
    type: "running",
    message: "Collecting LG Electronics data...",
  },
  {
    delay: 3500,
    agent: "worker_a",
    type: "success",
    message:
      "Completed (1,240 tokens) - Samsung Electronics FY2024 revenue reached 300T KRW...",
  },
  {
    delay: 4200,
    agent: "worker_b",
    type: "success",
    message:
      "Completed (980 tokens) - LG Electronics operating profit reached 3.5T KRW...",
  },
  {
    delay: 5000,
    agent: "orchestrator",
    type: "interrupt",
    message: "Should we include SK Hynix in the analysis scope as well?",
  },
  {
    delay: 7000,
    agent: "worker_a",
    type: "running",
    message: "Collecting SK Hynix data...",
  },
  {
    delay: 9000,
    agent: "worker_a",
    type: "success",
    message:
      "Completed (1,100 tokens) - SK Hynix HBM revenue shows sharp growth...",
  },
  {
    delay: 10000,
    agent: "reviewer",
    type: "running",
    message: "Validating final report...",
  },
  {
    delay: 12000,
    agent: "reviewer",
    type: "success",
    message: "Validation complete - final score: 94.2",
  },
];
